version: 2
jobs:
  build:
    docker:
    - image: golang:1.12
    steps:
    - checkout
    - setup_remote_docker:
      version: 18.06.0-ce
    - run:
      name: test
      shell: /bin/bash
      environment:
        TTT: ttt
      command: |
        echo "test"
        env
