version: 2
jobs:
  aaa:
    docker:
    - image: golang:1.12
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run:
        name: test
        shell: /bin/bash
        environment:
          TTT: ttt
        command: |
          echo "test aaa"
          env
  ccc:
    docker:
    - image: golang:1.12
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run:
        name: test
        shell: /bin/bash
        environment:
          TTT: ttt
        command: |
          echo "test ccc"
          env
  bbb:
    docker:
    - image: golang:1.12
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run:
        name: test
        shell: /bin/bash
        environment:
          TTT: ttt
        command: |
          echo "test bbb"
          env
workflows:
  version: 2
  build_test:
    jobs:
      - bbb

